[package]
name = "rust-text-processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
clap = { version = "4.5.9", features = ["derive"] }
rayon = "1.10.0"
crossbeam = "0.8.4"
